rewritten profile (now zshrc) and cleaned up a number of items in defaults to accounbt for changes in macos Catalina.

diff --git a/init/zshrc b/init/zshrc
--- a/init/zshrc
+++ b/init/zshrc
@@ -1,41 +1,109 @@
-########################################################## Credits; Diego Iaconelli
+############################################################################### 
+# Credits; Diego Iaconelli
 # Source; https://github.com/matdotcx/
 # Initial Version; Mon 29 Aug 2013 03:12:04 BST
 ###############################################################################
 
-# System-wide .profile for sh(1)
+#!/bin/zsh
 
 export LANG=en_GB.UTF-8
 
 ###############################################################################
-# Declaration of the prompt, shell, paths, motd.
+# zsh specifics
 ###############################################################################
 
+HISTFILE=~/.zsh_history
+HISTSIZE=1000
+SAVEHIST=1000
+setopt autocd beep nomatch prompt_subst correct inc_append_history interactivecomments share_history
+unsetopt notify
+zstyle :compinstall filename "$HOME/.zshrc"
+autoload -Uz compinit && compinit
+autoload -U colors && colors # Enable colors in prompt
 
-export PATH='/usr/local/sbin:$PATH'
+###############################################################################
+# Prompt & motd 
+###############################################################################
 
-if [ -x /usr/libexec/path_helper ]; then
-	eval `/usr/libexec/path_helper -s`
-fi
+# Echoes information about Git repository status when inside a Git repository
+git_info() {
 
-if [ "${BASH-no}" != "no" ]; then
-	[ -r /etc/bashrc ] && . /etc/bashrc
-fi
+  # Exit if not inside a Git repository
+  ! git rev-parse --is-inside-work-tree > /dev/null 2>&1 && return
+
+  # Git branch/tag, or name-rev if on detached head
+  local GIT_LOCATION=${$(git symbolic-ref -q HEAD || git name-rev --name-only --no-undefined --always HEAD)#(refs/heads/|tags/)}
+
+  local AHEAD="%{$fg[red]%}⇡NUM%{$reset_color%}"
+  local BEHIND="%{$fg[cyan]%}⇣NUM%{$reset_color%}"
+  local MERGING="%{$fg[magenta]%}⚡︎%{$reset_color%}"
+  local UNTRACKED="%{$fg[red]%}●%{$reset_color%}"
+  local MODIFIED="%{$fg[yellow]%}●%{$reset_color%}"
+  local STAGED="%{$fg[green]%}●%{$reset_color%}"
+
+  local -a DIVERGENCES
+  local -a FLAGS
+
+  local NUM_AHEAD="$(git log --oneline @{u}.. 2> /dev/null | wc -l | tr -d ' ')"
+  if [ "$NUM_AHEAD" -gt 0 ]; then
+    DIVERGENCES+=( "${AHEAD//NUM/$NUM_AHEAD}" )
+  fi
+
+  local NUM_BEHIND="$(git log --oneline ..@{u} 2> /dev/null | wc -l | tr -d ' ')"
+  if [ "$NUM_BEHIND" -gt 0 ]; then
+    DIVERGENCES+=( "${BEHIND//NUM/$NUM_BEHIND}" )
+  fi
+
+  local GIT_DIR="$(git rev-parse --git-dir 2> /dev/null)"
+  if [ -n $GIT_DIR ] && test -r $GIT_DIR/MERGE_HEAD; then
+    FLAGS+=( "$MERGING" )
+  fi
+
+  if [[ -n $(git ls-files --other --exclude-standard 2> /dev/null) ]]; then
+    FLAGS+=( "$UNTRACKED" )
+  fi
+
+  if ! git diff --quiet 2> /dev/null; then
+    FLAGS+=( "$MODIFIED" )
+  fi
+
+  if ! git diff --cached --quiet 2> /dev/null; then
+    FLAGS+=( "$STAGED" )
+  fi
+
+  local -a GIT_INFO
+  GIT_INFO+=( "\033[38;5;15m±" )
+  [[ ${#DIVERGENCES[@]} -ne 0 ]] && GIT_INFO+=( "${(j::)DIVERGENCES}" )
+  [[ ${#FLAGS[@]} -ne 0 ]] && GIT_INFO+=( "${(j::)FLAGS}" )
+  GIT_INFO+=( "\033[38;5;15m$GIT_LOCATION%{$reset_color%}" )
+  echo "${(j: :)GIT_INFO}"
+
+}
 
 echo
 echo "» salva nos, stella maris!"
 echo "Welcome to "`scutil --get ComputerName`"! | "`sw_vers -productName`"`if serverinfo -q --configured; then echo  " Server"; else echo " Client"; fi`" - `sw_vers -productVersion`"" "(`sw_vers -buildVersion`)"
-bash /etc/uptime.sh
+zsh /etc/uptime.sh
 date "+%A, %B %d, %Y | %T %Z"
 echo
 
+# Use → as the non-root prompt character; # for root
+# Change the prompt character color if the last command had a nonzero exit code
 
-export PS1="\[\e[31m\]→\[\e[m\] \[\e[31m\]\u\[\e[m\] @ \H\n\[\e[31m\]→ \[\e[m\]"
-export SUDO_PS1="\[\e[35m\]→\[\e[m\] \[\e[35m\]\u\[\e[m\] @ \H\n\[\e[35m\]→ \[\e[m\]"
+PS1='
+%{$fg[magenta]%}%~%u $(git_info)%{$reset_color%}
+%(?.%{$fg[red]%}.%{$fg[blue]%})%(!.#.→ %n)%{$reset_color%} @ %M 
+%{$fg[red]%}% → $reset_color%}'
 
+# LSCOLORS - Default except for normal directories (first character) to replace hard-to-read blue
+# For details, see manpage for ls
+export LSCOLORS=Gxfxcxdxbxegedabagacad
+
+# Set up diff-highlight
+export PATH=$GIT_DIFF_HIGHLIGHT_PATH:$PATH
 
 ###############################################################################
-# Shell % Navigation
+# Shell & Navigation
 ###############################################################################
 
 # Always use color output for `ls`
@@ -63,10 +131,6 @@ man() {
 		LESS_TERMCAP_us=$(printf "\e[1;32m") \
 			man "$@"
 }
- 
-# Add colour - see https://github.com/garabik/grc
-# Requires 'brew install grc'
-source "`brew --prefix`/etc/grc.bashrc"
 
 # Show all invisible files…
 alias show='defaults write com.apple.finder AppleShowAllFiles TRUE; killall Finder'
@@ -101,10 +165,8 @@ alias cdh='cd ~/'
 alias ll='ls -AlhGti'
 
 # Generates a tree of files from the current working directory
-alias filetree="ls -R | grep ":$" | sed -e 's/:$//' -e 's/[^-][^\/]*\//--/g' -e 's/^/ /' -e 's/-/|/'"
+alias tree="ls -R | grep ":$" | sed -e 's/:$//' -e 's/[^-][^\/]*\//--/g' -e 's/^/ /' -e 's/-/|/'"
 
-# Bring up TextMate with the /profile as the open document
-alias profile='mate /etc/profile'
 
 ###############################################################################
 # Network
@@ -128,7 +190,7 @@ function digga() {
 ###############################################################################
 
 # Flush Directory Service cache
-alias flush="dscacheutil -flushcache && killall -HUP mDNSResponder"
+alias flush="dscacheutil -flushcache "
 
 # Clean up LaunchServices to remove duplicates in the “Open With” menu
 alias lscleanup="/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user && killall Finder"
@@ -146,19 +208,19 @@ command -v md5sum > /dev/null || alias md5sum="md5"
 command -v sha1sum > /dev/null || alias sha1sum="shasum"
 
 # Generate a password using haddock, length of 28 characters. 
+# sudo gem install haddock -n /usr/local/bin
 alias secret='ha-gen -l 28'
 
 # Get macOS Software Updates, and update installed Ruby gems, Homebrew, npm, and their installed packages
 alias update='sudo softwareupdate -i -a; brew update; brew upgrade; brew cleanup; npm install npm -g; npm update -g; sudo gem update --system; sudo gem update; sudo gem cleanup'
 
 # Suspend current account - effectively go to sleep and present login window
-alias suspend='/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend'
+# This is currently commented out due to performance issues in Catalina
+# alias suspend='/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend'
 
+# Locks current account - present the Screensaver and User Login.
+alias lock='/System/Library/CoreServices/ScreenSaverEngine.app/Contents/MacOS/ScreenSaverEngine'
 
-
-
-
-
-
-
-
+# Add colour - see https://github.com/garabik/grc
+# Requires `brew install grc`, presuming grc is installed to usr/local/etc/
+[[ -s "/usr/local/etc/grc.zsh" ]] && source /usr/local/etc/grc.zsh
